---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: hdd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: st1
  encrypted: "true"